import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  // {
  //   path: '/dashboard/main',
  //   title: 'MENUITEMS.HOME.LIST.DASHBOARD1',
  //   iconType: 'feather',
  //   icon: 'trello',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },
  // {
  //   path: '/dashboard/dashboard2',
  //   title: 'MENUITEMS.HOME.LIST.DASHBOARD2',
  //   iconType: 'feather',
  //   icon: 'trello',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },

  {
    path: 'all-clients',
    title: 'MENUITEMS.ALL-CLIENTS.TEXT',
    iconType: 'feather',
    icon: 'user-check',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'to-do',
    title: 'MENUITEMS.TO-DO.TEXT',
    iconType: 'feather',
    icon: 'list',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'delete-checks',
    title: 'MENUITEMS.DELETE-CHECKS.TEXT',
    iconType: 'feather',
    icon: 'trello',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
];
